# Generated by Django 4.2.3 on 2023-07-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Population_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='population',
            name='limit',
        ),
        migrations.AddField(
            model_name='population',
            name='is_capital',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='population',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='population',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
    ]
